/*
 * This source file was generated by the Gradle 'init' task
 */
package com.game;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GameAppTest {
    @Test void appHasAGreeting() {
        GameApp classUnderTest = new GameApp();
    }
}
